addSbtPlugin("org.typelevel" % "sbt-typelevel-ci-release" % "0.8.6")
addSbtPlugin("org.typelevel" % "sbt-typelevel-settings" % "0.8.6")
addSbtPlugin("org.typelevel" % "sbt-typelevel-mergify" % "0.8.6")
addSbtPlugin("org.scala-js" % "sbt-scalajs" % "1.22.0")
addSbtPlugin("org.portable-scala" % "sbt-scalajs-crossproject" % "1.3.2")
